# Generated by Django 5.2.5 on 2025-08-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_role_useraccount_created_at_useraccount_created_by_and_more'),
        ('registration', '0002_alter_useraccount_role_alter_useraccount_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
