# Generated by Django 5.2.5 on 2025-08-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
