# Generated by Django 5.2.5 on 2025-08-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('role', '0002_alter_role_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='role.role'),
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table='user_registration',
        ),
    ]
