# Generated by Django 5.2.5 on 2025-08-19 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_useraccount_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default=999999999, max_length=15),
            preserve_default=False,
        ),
    ]
