# Generated by Django 5.2.5 on 2025-08-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='user_roles',
        ),
    ]
